/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bohiogym;

import entity.UserInfo;
import entity.UserLog;
import entity.UserPermisos;
import java.awt.event.KeyEvent;
import javax.persistence.EntityManagerFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jpa.GymPermisosJpaController;
import jpa.UserInfoJpaController;
import jpa.UserLogJpaController;
import jpa.UserPermisosJpaController;

/**
 *
 * @author Juan
 */
public class confinicial extends javax.swing.JDialog {

    private final EntityManagerFactory factory;
    UserLog userLog = null;
    UserLogJpaController uljc = null;
    UserInfo userInfo = null;
    UserInfoJpaController uijc = null;
    UserPermisos userPermisos = null;
    UserPermisosJpaController upjc = null;
    GymPermisosJpaController gpjc = null;
    ImageIcon check = new ImageIcon(getClass().getResource("/recursos/check20.png"));
    ImageIcon error = new ImageIcon(getClass().getResource("/recursos/error20.png"));
    boolean claves = false;

    /**
     * Creates new form confinicial
     */
    public confinicial(java.awt.Frame parent, boolean modal, EntityManagerFactory factory) {
        super(parent, modal);
        initComponents();
        this.factory = factory;
        LVerificacion.setText(null);
    }

    private void verificarClave() {
        if (PClave.getText().equals(PCClave.getText())) {
            LVerificacion.setIcon(check);
            claves = true;
        } else {
            LVerificacion.setIcon(error);
            claves = false;
        }
    }

    private void crearUserInicial() {
        if (TUsuario.getText() == null || TUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un usuario");
        } else if (PClave == null || PClave.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una clave");
        } else if (!claves) {
            JOptionPane.showMessageDialog(null, "Las claves no coinciden");
        } else if (tIdentificacion.getText() == null || tIdentificacion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una identificacion");
        } else if (tNombres.getText() == null || tNombres.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre");
        } else if (tApellidos.getText() == null || tApellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un apellido");
        } else {
            userLog = new UserLog();
            userLog.setUsuario(TUsuario.getText().toUpperCase());
            userLog.setClave(PCClave.getText());
            userLog.setEstado(1);
            if (uljc == null) {
                uljc = new UserLogJpaController(factory);
            }
            uljc.create(userLog);
            userInfo = new UserInfo();
            userInfo.setIdentificacion(tIdentificacion.getText());
            userInfo.setNombres(tNombres.getText().toUpperCase());
            userInfo.setApellidos(tApellidos.getText().toUpperCase());
            userInfo.setIdlog(userLog);
            userInfo.setEstado(1);
            if (uijc == null) {
                uijc = new UserInfoJpaController(factory);
            }
            uijc.create(userInfo);
            if (gpjc == null) {
                gpjc = new GymPermisosJpaController(factory);
            }
            userPermisos = new UserPermisos();
            userPermisos.setIduser(userLog);
            userPermisos.setIdpermiso(gpjc.findGymPermisosEntities().get(0));
            userPermisos.setEstado(2);
            if (upjc == null) {
                upjc = new UserPermisosJpaController(factory);
            }
            upjc.create(userPermisos);
            JOptionPane.showMessageDialog(null, "Usuario creado Exitosamente");
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PClave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        PCClave = new javax.swing.JPasswordField();
        LVerificacion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        tNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tApellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tIdentificacion = new javax.swing.JTextField();
        bConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(50, 72, 141));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Configuracion Inicial");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Usuario:");

        TUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TUsuarioKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Clave:");

        PClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PClaveKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Confirmar Clave:");

        PCClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PCClaveKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PCClaveKeyReleased(evt);
            }
        });

        LVerificacion.setText("jLabel5");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombres:");

        tNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNombresKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Apellidos:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Identificación:");

        tIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tIdentificacionKeyPressed(evt);
            }
        });

        bConfirmar.setBackground(new java.awt.Color(50, 72, 141));
        bConfirmar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        bConfirmar.setText("Confirmar");
        bConfirmar.setContentAreaFilled(false);
        bConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConfirmar.setFocusable(false);
        bConfirmar.setOpaque(true);
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LVerificacion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PCClave, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PClave, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tIdentificacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNombres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(LVerificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PCClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PCClaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PCClaveKeyReleased
        verificarClave();
    }//GEN-LAST:event_PCClaveKeyReleased

    private void TUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            PClave.requestFocus();
        }
    }//GEN-LAST:event_TUsuarioKeyPressed

    private void PClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PClaveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            PCClave.requestFocus();
        }
    }//GEN-LAST:event_PClaveKeyPressed

    private void PCClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PCClaveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tIdentificacion.requestFocus();
        }
    }//GEN-LAST:event_PCClaveKeyPressed

    private void tIdentificacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tIdentificacionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tNombres.requestFocus();
        }
    }//GEN-LAST:event_tIdentificacionKeyPressed

    private void tNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombresKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tApellidos.requestFocus();
        }
    }//GEN-LAST:event_tNombresKeyPressed

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        crearUserInicial();
    }//GEN-LAST:event_bConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confinicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confinicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confinicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confinicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                confinicial dialog = new confinicial(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LVerificacion;
    private javax.swing.JPasswordField PCClave;
    private javax.swing.JPasswordField PClave;
    public javax.swing.JTextField TUsuario;
    private javax.swing.JButton bConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tApellidos;
    private javax.swing.JTextField tIdentificacion;
    private javax.swing.JTextField tNombres;
    // End of variables declaration//GEN-END:variables
}
